In [2]:
from matplotlib import pyplot as plt
from math import *
import numpy as np
import scipy
import sympy
# 该文件用作检验比对

In [7]:
N=10

def mod(idx):
    if(idx<0):
        return idx+N
    elif(idx>=N):
        return idx-N
    else:
        return idx

def delta(i,j):
    return 1 if mod(i) == mod(j) else 0

def f(i,j):
    return delta(i-1,j)+delta(i+1,j)-2*delta(i,j)
mat = [[f(i,j) for i in range(N)] for j in range(N)]
arr=np.matrix(mat,dtype='float')
print(arr)

[[-2.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1. -2.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -2.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -2.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -2.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -2.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. -2.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -2.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -2.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1. -2.]]


In [6]:
np.linalg.eig(arr)

(array([ 2.22044605e-16, -3.81966011e-01, -1.38196601e+00, -2.61803399e+00,
        -4.00000000e+00, -3.61803399e+00, -3.81966011e-01, -1.38196601e+00,
        -2.61803399e+00, -3.61803399e+00]),
 matrix([[ 0.31622777,  0.4472136 , -0.4472136 , -0.4472136 ,  0.31622777,
          -0.4472136 , -0.22120632, -0.00898918, -0.00931949, -0.0519836 ],
         [ 0.31622777,  0.3618034 , -0.1381966 ,  0.1381966 , -0.31622777,
           0.3618034 ,  0.04949739,  0.42246167,  0.42811292,  0.30313928],
         [ 0.31622777,  0.1381966 ,  0.3618034 ,  0.3618034 ,  0.31622777,
          -0.1381966 ,  0.30129478,  0.27008485, -0.25526885, -0.43850606],
         [ 0.31622777, -0.1381966 ,  0.3618034 , -0.3618034 , -0.31622777,
          -0.1381966 ,  0.4380078 , -0.25554005, -0.2703481 ,  0.40637843],
         [ 0.31622777, -0.3618034 , -0.1381966 , -0.1381966 ,  0.31622777,
           0.3618034 ,  0.40741673, -0.42801728,  0.42235316, -0.21902805],
         [ 0.31622777, -0.4472136 , -0.4472136 , 